config/routes.rb
Rails.application.routes.draw do
  get "/athletes", to: "athletes#index"

  get "/roster", to: "roster#index"

  root to: 'home#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/athletes_controller.rb
class AthletesController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/roster_controller.rb
class RosterController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/athletes_helper.rb
module AthletesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/roster_helper.rb
module RosterHelper
end

app/views/athletes/index.html.erb
<h1>Athletes#index</h1>

<p> hello </p> 
<p>Find me in app/views/athletes/index.html.erb</p>

app/views/home/_sidebar.html.erb
<% content_for :sidebar_links do %>


        


<% end %>

<div><%= link_to 'Roster', roster_path %> hello</div>

app/views/home/index.html.erb
<h1>Home</h1>

<h2> roster link </h2>

<%= render 'sidebar' %>


<p> This should link to the page for athletes
on a given team. Based on user will have 
permissions to certain athletes. Can 
rework this route later. But for now, 
want to be able to nav to a list of 
athletes and then from those athletes we can 
link to their pages with their stats. 
 </p> 

app/views/home/team_roster.html.erb
<h1>Roster</h1>

This should display a list of rosters and you can click on each 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>